# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 09:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='Aditya', max_length=120)),
                ('monthly_forcast', models.PositiveIntegerField(default=60)),
                ('monthly_forcast_update', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Forcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forcast', models.PositiveIntegerField(default=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('extended_communication', models.BooleanField(default=False)),
                ('durability', models.BooleanField(default=False)),
                ('inventory_cost', models.PositiveIntegerField(default=4)),
                ('monthly_order1', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Marks and Maxwell')),
                ('monthly_order2', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Chopra and Company')),
                ('monthly_order3', models.PositiveIntegerField(default=0, help_text='Max Value is 30', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Daggit Enterprises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
