# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_remove_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='employee_name',
            new_name='employee_name1',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='monthly_forcast',
            new_name='monthly_forcast1',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='monthly_forcast_update',
            new_name='monthly_forcast2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='extended_communication',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='storage',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='style',
            new_name='gesture',
        ),
        migrations.RemoveField(
            model_name='forcast',
            name='user',
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name2',
            field=models.CharField(default='Aditya', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name3',
            field=models.CharField(default='Aditya', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='employee_name4',
            field=models.CharField(default='Aditya', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast3',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast4',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast_update1',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast_update2',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast_update3',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast_update4',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='product',
            name='bull_whip_factor',
            field=models.BooleanField(default=False, verbose_name='Disclose the demand with Vendors'),
        ),
    ]
