# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20171012_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='employee_name4',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_forcast4',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='monthly_forcast_update4',
        ),
    ]
