# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20171012_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='employee_name4',
            field=models.CharField(default='Aditya', max_length=120),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast4',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='demand',
            name='monthly_forcast_update4',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
