# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 08:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20171014_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('gestures', models.BooleanField(default=False)),
                ('durability', models.BooleanField(default=False)),
                ('inventory_cost', models.PositiveIntegerField(default=4)),
                ('monthly_order1', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Marks and Maxwell')),
                ('monthly_order2', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Chopra and Company')),
                ('monthly_order3', models.PositiveIntegerField(default=0, help_text='Max Value is 30', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Daggit Enterprises')),
                ('bull_whip_factor', models.BooleanField(default=False, verbose_name='Disclose the demand with Vendors')),
                ('mod_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('gestures', models.BooleanField(default=False)),
                ('durability', models.BooleanField(default=False)),
                ('inventory_cost', models.PositiveIntegerField(default=4)),
                ('monthly_order1', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Marks and Maxwell')),
                ('monthly_order2', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Chopra and Company')),
                ('monthly_order3', models.PositiveIntegerField(default=0, help_text='Max Value is 30', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Daggit Enterprises')),
                ('bull_whip_factor', models.BooleanField(default=False, verbose_name='Disclose the demand with Vendors')),
                ('mod_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('gestures', models.BooleanField(default=False)),
                ('durability', models.BooleanField(default=False)),
                ('inventory_cost', models.PositiveIntegerField(default=4)),
                ('monthly_order1', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Marks and Maxwell')),
                ('monthly_order2', models.PositiveIntegerField(default=0, help_text='Max Value is 45', validators=[django.core.validators.MaxValueValidator(45)], verbose_name='Chopra and Company')),
                ('monthly_order3', models.PositiveIntegerField(default=0, help_text='Max Value is 30', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Daggit Enterprises')),
                ('bull_whip_factor', models.BooleanField(default=False, verbose_name='Disclose the demand with Vendors')),
                ('mod_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mod_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
